project_id = "kbaazksvkvnafrwtmkcw"

[functions.process-device-photos]
verify_jwt = true

[functions.process-user-query]


[functions.create-task]
verify_jwt = false


[functions.openrouter-task-call]
verify_jwt = false


[functions.ogemath-task-hardcode]
verify_jwt = false


[functions.student-progress-calculate]
verify_jwt = false

[functions.log-textbook-activity]


[functions.analyze-photo-solution]

verify_jwt = false

[functions.check-photo-solution]
verify_jwt = false


[functions.boost-low-mastery-skills]
verify_jwt = true


[functions.weekly-energy-points-reset]
verify_jwt = false

[db]
major_version = 15

